CREATE DATABASE IF NOT EXISTS db_pw2;
USE db_pw2;

CREATE TABLE login (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    email VARCHAR(100) NOT NULL,
    idade VARCHAR(40),
    id_login INT NOT NULL,
    FOREIGN KEY (id_login) REFERENCES login(id) ON DELETE CASCADE
);

--CRIAR UMA TABELA DE PRODUTO

CREATE TABLE produto (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	nome VARCHAR (100) NOT NULL,
	marca VARCHAR (100) NOT NULL,
	preco VARCHAR (30) NOT NULL,
	descricao VARCHAR (150),
	quantidade INT NOT NULL,
	categoria VARCHAR (30) NOT NULL,
	caminho_do_produto VARCHAR (80)NOT NULL,
	data_cadastro VARCHAR (10) NOT NULL,
	ativo VARCHAR (5) NOT NULL,
);